-- Grant permissions to API_ACCESS_ROLE for DEMO_V4 database and CORRELATED_SCHEMA
-- This script should be run by a user with ACCOUNTADMIN or similar privileges

-- Switch to ACCOUNTADMIN role (ensure you have the right privileges)
USE ROLE ACCOUNTADMIN;

-- Grant USAGE on the database
GRANT USAGE ON DATABASE DEMO_V4 TO ROLE API_ACCESS_ROLE;

-- Grant USAGE on the schema
GRANT USAGE ON SCHEMA DEMO_V4.CORRELATED_SCHEMA TO ROLE API_ACCESS_ROLE;

-- Grant SELECT on all existing tables in the schema
GRANT SELECT ON ALL TABLES IN SCHEMA DEMO_V4.CORRELATED_SCHEMA TO ROLE API_ACCESS_ROLE;

-- Grant SELECT on all future tables in the schema
GRANT SELECT ON FUTURE TABLES IN SCHEMA DEMO_V4.CORRELATED_SCHEMA TO ROLE API_ACCESS_ROLE;

-- For the USER_CONVERSATIONS table specifically, grant full CRUD permissions
-- (needed for the memory system to read and write conversation history)
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE DEMO_V4.CORRELATED_SCHEMA.USER_CONVERSATIONS TO ROLE API_ACCESS_ROLE;

-- Grant USAGE on the warehouse (if not already granted)
GRANT USAGE ON WAREHOUSE COMPUTE_WH TO ROLE API_ACCESS_ROLE;

-- Optional: Grant CREATE TABLE privilege if the system needs to create new tables
-- GRANT CREATE TABLE ON SCHEMA DEMO_V4.CORRELATED_SCHEMA TO ROLE API_ACCESS_ROLE;

-- Verify the grants were applied
SHOW GRANTS TO ROLE API_ACCESS_ROLE;

-- Display a success message
SELECT 'Permissions granted successfully to API_ACCESS_ROLE for DEMO_V4.CORRELATED_SCHEMA' AS STATUS;

-- Specific grants for individual tables (alternative approach if the above doesn't work)
/*
GRANT SELECT ON TABLE DEMO_V4.CORRELATED_SCHEMA.FINANCIAL_DATA TO ROLE API_ACCESS_ROLE;
GRANT SELECT ON TABLE DEMO_V4.CORRELATED_SCHEMA.LEADS TO ROLE API_ACCESS_ROLE;
GRANT SELECT ON TABLE DEMO_V4.CORRELATED_SCHEMA.OPPORTUNITIES TO ROLE API_ACCESS_ROLE;
GRANT SELECT ON TABLE DEMO_V4.CORRELATED_SCHEMA.POC_TRACKER TO ROLE API_ACCESS_ROLE;
GRANT SELECT ON TABLE DEMO_V4.CORRELATED_SCHEMA.QUOTES TO ROLE API_ACCESS_ROLE;
GRANT SELECT ON TABLE DEMO_V4.CORRELATED_SCHEMA.SUPPORT_TICKETS TO ROLE API_ACCESS_ROLE;
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE DEMO_V4.CORRELATED_SCHEMA.USER_CONVERSATIONS TO ROLE API_ACCESS_ROLE;
*/ 